### ISSUE TITLE
Call detection error

### ISSUE THREAD

**Issue by paloke** [AT0myks/pycallblock#2]
Thank you for providing the program. 

Unfortunately, I have encountered some issues with it. I have included a log file that details the errors I have encountered. I would appreciate it if you could take a look and help me resolve the issue. 

Thank you for your assistance. 

Best regards,

```
2023-11-06 14:57:25,069 INFO: pycallblock 1.0.0 is starting
2023-11-06 14:57:25,069 INFO: Audio file: None
2023-11-06 14:57:25,069 INFO: Block action: None
2023-11-06 14:57:25,069 INFO: Block private numbers: False
2023-11-06 14:57:25,069 INFO: Filter list: /home/jc/pycallblock/block.csv
2023-11-06 14:57:25,069 INFO: Filter type: FilterType.BLACKLIST
2023-11-06 14:57:25,069 INFO: Max voice duration: None
2023-11-06 14:57:25,069 INFO: Silence seconds: None
2023-11-06 14:57:25,069 INFO: Timezone: None
2023-11-06 14:57:25,279 DEBUG: CommandResponse('ATZ', None, <ResultCode.OK: 'OK'>, b'ATZ\r\r\nOK\r\n')
2023-11-06 14:57:25,282 DEBUG: CommandResponse('AT+FCLASS?', '0', <ResultCode.OK: 'OK'>, b'AT+FCLASS?\r\r\n0\r\nOK\r\n')
2023-11-06 14:57:25,287 DEBUG: CommandResponse('AT+VCID=1', None, <ResultCode.OK: 'OK'>, b'AT+VCID=1\r\r\nOK\r\n')
2023-11-06 14:57:25,290 DEBUG: CommandResponse('AT+FCLASS=0', None, <ResultCode.OK: 'OK'>, b'AT+FCLASS=0\r\r\nOK\r\n')
2023-11-06 14:57:25,290 INFO: Mode has been set to Mode.DATA
2023-11-06 14:57:25,291 INFO: Waiting event...
2023-11-06 14:58:32,768 ERROR: Exception in background task event_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 730, in done_callback
    task.result()
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 714, in event_loop
    event = Event.from_bytes(bytes_)
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 168, in from_bytes
    key, val = part.split(" = ")
ValueError: not enough values to unpack (expected 2, got 1)
2023-11-06 14:58:32,769 INFO: Waiting event...
2023-11-06 14:58:32,770 ERROR: Exception in background task event_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 730, in done_callback
    task.result()
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 714, in event_loop
    event = Event.from_bytes(bytes_)
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 168, in from_bytes
    key, val = part.split(" = ")
ValueError: not enough values to unpack (expected 2, got 1)
2023-11-06 14:58:32,771 INFO: Waiting event...
2023-11-06 14:58:34,698 DEBUG: Event('RING', b'\r\nRING\r\n', 1699279114698353934)
2023-11-06 14:58:34,698 INFO: Ringing...
2023-11-06 14:58:34,698 INFO: Waiting event...
2023-11-06 14:58:39,274 DEBUG: Event('RING', b'\r\nRING\r\n', 1699279119274316282)
2023-11-06 14:58:39,274 INFO: Ringing...
2023-11-06 14:58:39,274 INFO: Waiting event...
2023-11-06 14:58:43,839 DEBUG: Event('RING', b'\r\nRING\r\n', 1699279123839238831)
2023-11-06 14:58:43,839 INFO: Ringing...
2023-11-06 14:58:43,839 INFO: Waiting event...
2023-11-06 14:58:47,751 DEBUG: Event('RING', b'\r\nRING\r\n', 1699279127751297117)
2023-11-06 14:58:47,751 INFO: Ringing...
2023-11-06 14:58:47,751 INFO: Waiting event...

```

**Comment by AT0myks** [comment]
Thank you for the logs. I released v1.0.1 which shows the event data that causes this error. Please update (`pip install -U pycallblock`) and run again so that we can see exactly what the modem is sending. Don't forget to remove any personal information.

**Comment by paloke** [comment]
Thanks for the new development, here I leave the new log, the phone number has been changed to 987654321.

I am using the trendnet tfm-561u modem.

```
2023-11-07 11:12:37,483 INFO: pycallblock 1.0.1 is starting
2023-11-07 11:12:37,485 INFO: Audio file: None
2023-11-07 11:12:37,485 INFO: Block action: None
2023-11-07 11:12:37,485 INFO: Block private numbers: False
2023-11-07 11:12:37,485 INFO: Filter list: /home/kd/pycallblock/block.csv
2023-11-07 11:12:37,485 INFO: Filter type: FilterType.BLACKLIST
2023-11-07 11:12:37,485 INFO: Max voice duration: None
2023-11-07 11:12:37,485 INFO: Silence seconds: None
2023-11-07 11:12:37,485 INFO: Timezone: None
2023-11-07 11:12:37,699 DEBUG: CommandResponse('ATZ', None, <ResultCode.OK: 'OK'>, b'ATZ\r\r\nOK\r\n')
2023-11-07 11:12:37,703 DEBUG: CommandResponse('AT+FCLASS?', '0', <ResultCode.OK: 'OK'>, b'AT+FCLASS?\r\r\n0\r\nOK\r\n')
2023-11-07 11:12:37,708 DEBUG: CommandResponse('AT+VCID=1', None, <ResultCode.OK: 'OK'>, b'AT+VCID=1\r\r\nOK\r\n')
2023-11-07 11:12:37,712 DEBUG: CommandResponse('AT+FCLASS=0', None, <ResultCode.OK: 'OK'>, b'AT+FCLASS=0\r\r\nOK\r\n')
2023-11-07 11:12:37,712 INFO: Mode has been set to Mode.DATA
2023-11-07 11:12:37,712 INFO: Waiting event...
2023-11-07 11:51:31,493 ERROR: Could not parse event data: b'\r\nDATE = 1107\r\nTIME = 1152\r\nNMBR'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 716, in event_loop
    event = Event.from_bytes(bytes_)
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 168, in from_bytes
    key, val = part.split(" = ")
ValueError: not enough values to unpack (expected 2, got 1)
2023-11-07 11:51:31,494 INFO: Waiting event...
2023-11-07 11:51:31,495 ERROR: Could not parse event data: b' = 987654321\r\nNAME = P\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 716, in event_loop
    event = Event.from_bytes(bytes_)
  File "/usr/local/lib/python3.9/dist-packages/pycallblock/modem.py", line 168, in from_bytes
    key, val = part.split(" = ")
ValueError: not enough values to unpack (expected 2, got 1)
2023-11-07 11:51:31,495 INFO: Waiting event...
2023-11-07 11:51:33,422 DEBUG: Event('RING', b'\r\nRING\r\n', 1699354293422830345)
2023-11-07 11:51:33,423 INFO: Ringing...
2023-11-07 11:51:33,423 INFO: Waiting event...
2023-11-07 11:51:37,980 DEBUG: Event('RING', b'\r\nRING\r\n', 1699354297980791295)
2023-11-07 11:51:37,980 INFO: Ringing...
2023-11-07 11:51:37,980 INFO: Waiting event...
2023-11-07 11:51:42,574 DEBUG: Event('RING', b'\r\nRING\r\n', 1699354302574820680)
2023-11-07 11:51:42,574 INFO: Ringing...
2023-11-07 11:51:42,575 INFO: Waiting event...
2023-11-07 11:52:40,289 INFO: Received SIGINT
2023-11-07 11:52:40,289 INFO: Stopping...
2023-11-07 11:52:40,350 DEBUG: Background task event_loop is done
2023-11-07 11:52:40,355 DEBUG: CommandResponse('ATZ', None, <ResultCode.OK: 'OK'>, b'ATZ\r\r\nOK\r\n')
2023-11-07 11:52:40,359 DEBUG: CommandResponse('AT+FCLASS?', '0', <ResultCode.OK: 'OK'>, b'AT+FCLASS?\r\r\n0\r\nOK\r\n')
2023-11-07 11:52:40,361 INFO: pycallblock stopped
```

**Comment by AT0myks** [comment]
This is the first time I see an event being split into multiple parts. [This page](https://en.wikipedia.org/wiki/Network_Caller_ID) says that your modem has a different chipset version than mine, maybe it has something to do with it. The first half of the data is 32 characters long, maybe it can't send more characters at once? I tried something in v1.0.2, please update again to see if that helps.

**Comment by paloke** [comment]
In this version, call detection works correctly.  I leave the last log for the command responses.

```
2023-11-08 10:22:22,489 INFO: pycallblock 1.0.2 is starting
2023-11-08 10:22:22,489 INFO: Audio file: None
2023-11-08 10:22:22,489 INFO: Block action: None
2023-11-08 10:22:22,489 INFO: Block private numbers: False
2023-11-08 10:22:22,489 INFO: Filter list: /home/le/pycallblock/block.csv
2023-11-08 10:22:22,489 INFO: Filter type: FilterType.BLACKLIST
2023-11-08 10:22:22,489 INFO: Max voice duration: None
2023-11-08 10:22:22,489 INFO: Silence seconds: None
2023-11-08 10:22:22,489 INFO: Timezone: None
2023-11-08 10:22:22,701 DEBUG: CommandResponse('ATZ', None, <ResultCode.OK: 'OK'>, b'ATZ\r\r\nOK\r\n')
2023-11-08 10:22:22,705 DEBUG: CommandResponse('AT+FCLASS?', '0', <ResultCode.OK: 'OK'>, b'AT+FCLASS?\r\r\n0\r\nOK\r\n')
2023-11-08 10:22:22,705 DEBUG: Device: '/dev/ttyACM0'
2023-11-08 10:22:22,707 DEBUG: CommandResponse('ATI3', 'CX93001-EIS_V0.2002-V92', <ResultCode.OK: 'OK'>, b'ATI3\r\r\nCX93001-EIS_V0.2002-V92\r\n\r\nOK\r\n')
2023-11-08 10:22:22,707 DEBUG: await self.get_masked_firmware_id_code()='CX93001-EIS_V0.2002-V92'
2023-11-08 10:22:22,710 DEBUG: CommandResponse('AT+GMI', 'CONEXANT', <ResultCode.OK: 'OK'>, b'AT+GMI\r\r\n+GMI: CONEXANT\r\n\r\nOK\r\n')
2023-11-08 10:22:22,710 DEBUG: await self.get_product_manufacturer()='CONEXANT'
2023-11-08 10:22:22,715 DEBUG: CommandResponse('AT+VCID=1', None, <ResultCode.OK: 'OK'>, b'AT+VCID=1\r\r\nOK\r\n')
2023-11-08 10:22:22,718 DEBUG: CommandResponse('AT+FCLASS=0', None, <ResultCode.OK: 'OK'>, b'AT+FCLASS=0\r\r\nOK\r\n')
2023-11-08 10:22:22,718 INFO: Mode has been set to Mode.DATA
2023-11-08 10:22:22,718 INFO: Waiting event...
2023-11-08 13:49:29,984 DEBUG: Event({'DATE': '1108', 'TIME': '1349', 'NMBR': '987654321', 'NAME': 'P'}, b'\r\nDATE = 1108\r\nTIME = 1349\r\nNMBR = 987654321\r\nNAME = P\r\n', 1699447769983943923)
2023-11-08 13:49:29,984 INFO: Receiving call: 987654321/P
2023-11-08 13:49:29,995 INFO: Call logged
2023-11-08 13:49:29,995 INFO: Waiting event...
2023-11-08 13:49:31,976 DEBUG: Event('RING', b'\r\nRING\r\n', 1699447771976524697)
2023-11-08 13:49:31,976 INFO: Ringing...
2023-11-08 13:49:31,976 INFO: Waiting event...
2023-11-08 13:49:36,514 DEBUG: Event('RING', b'\r\nRING\r\n', 1699447776514774687)
2023-11-08 13:49:36,514 INFO: Ringing...
2023-11-08 13:49:36,514 INFO: Waiting event...
2023-11-08 13:49:41,080 DEBUG: Event('RING', b'\r\nRING\r\n', 1699447781080815407)
2023-11-08 13:49:41,080 INFO: Ringing...
2023-11-08 13:49:41,080 INFO: Waiting event...

```

**Comment by AT0myks** [comment]
The chipset version is indeed different (mine is `CX93001-EIS_V0.2013-V92`). I'm not too happy with the fix but as long as it works it should be fine.
